server:
  port: 8080

spring:
  application:
    name: ticketing

  datasource:
    url: jdbc:mysql://localhost:3307/ticketing_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: joedaehui@ajou.ac.kr
    password: uryhzevwvzlezjmt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ticketing-secret-key-value
  expiration: 86400000




#  r2dbc:
#    url: r2dbc:mysql://localhost:3307/ticketing_db
#    username: root
#    password: 1234

#  kafka:
#    bootstrap-servers: localhost:9092 # Kafka 브로커 주소

#security:
#  oauth2:
#    client:
#      registration:
#        google:
#          client-id: your-google-client-id
#          client-secret: your-google-client-secret
#          scope: profile, email
